spring.application.name=tutorial


# JDBC URL for file-based H2 database
spring.datasource.url=jdbc:h2:file:./data/jwt
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret.key=_@_hunter_x_hunter_@_2_0_0_1_@_123456789_MERURO@ANIME_WATCH.TV

logging.level.org.springframework.security=DEBUG